x-common:
 tunnel: &tunnel
  - TUNNEL_TOKEN=
 panel: &panel
  APP_URL: https://
  APP_SERVICE_AUTHOR: default@gmail.com
  APP_TIMEZONE: &tz Pacific/Auckland
  DB_PASSWORD: &db-password mortuary-retinal-cosmic

networks:
 ptero:
  ipam:
   config:
    - subnet: 172.28.0.0/16

volumes:
 mariadb:
 dragonfly:
 panel_var:
 panel_srv:

services:
 panel:
  build:
   context: .
   dockerfile: Dockerfile
  restart: always
  volumes:
   - panel_srv:/srv/pterodactyl
   - panel_var:/app/var
  environment:
   <<: *panel
   APP_ENV: production
   APP_ENVIRONMENT_ONLY: false
   CACHE_DRIVER: redis
   SESSION_DRIVER: redis
   QUEUE_DRIVER: redis
   REDIS_HOST: dragonfly
   DB_HOST: mariadb
   DB_PORT: 3306
  networks:
   - ptero
  depends_on:
   - mariadb
   - dragonfly

 wings:
  build:
   context: ../wings
   dockerfile: Dockerfile
  restart: always
  tty: true
  environment:
   TZ: *tz
   WINGS_UID: 988
   WINGS_GID: 988
   WINGS_USERNAME: pterodactyl
  volumes:
   - ./:/etc/pterodactyl
   # Do not change any of the below mounts
   - /var/run/docker.sock:/var/run/docker.sock
   - /var/lib/docker/containers:/var/lib/docker/containers
   - /var/lib/pterodactyl:/var/lib/pterodactyl
   - /var/log/pterodactyl:/var/log/pterodactyl
   - /tmp/pterodactyl/:/tmp/pterodactyl/
  networks:
   - ptero
  depends_on:
   - panel

 tunnel:
  container_name: tunnel
  image: cloudflare/cloudflared
  restart: unless-stopped
  command: tunnel run
  environment:
   <<: *tunnel
  networks:
   - ptero

 mariadb:
  image: mariadb:latest
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - mariadb:/var/lib/mysql
  environment:
   MYSQL_PASSWORD: *db-password
   MYSQL_ROOT_PASSWORD: *db-password
   MYSQL_DATABASE: "panel"
   MYSQL_USER: "pterodactyl"
  networks:
   - ptero

 dragonfly:
  image: docker.dragonflydb.io/dragonflydb/dragonfly
  restart: always
  ulimits:
   memlock: -1
  volumes:
   - dragonfly:/data
  networks:
   - ptero
